### ISSUE TITLE
Shopee api v4

### ISSUE THREAD

**Issue by DestschEng** [Tran-Ngoc-Bao/Process_Shopee_Data#1]
Bạn ơi cho mình hỏi link api v4 lấy ở trang nào, hay api này là từ open api shopee  vậy ạ, mình cũng đang làm project crawl data trên shopee mà bị gặp block với captcha không biết bạn xử lý vấn đề như nào vậy n

**Comment by Tran-Ngoc-Bao** [comment]
Shopee họ chặn api bạn ạ
Bạn phải crawl bằng tay từ curl trên terminal và crawl 30p lại phải ngắt
quãng không họ chặn IP

Vào Th 6, 11 thg 10, 2024 lúc 09:14 DestschEng ***@***.***>
đã viết:

**Comment by DestschEng** [comment]
> Shopee họ chặn api bạn ạ Bạn phải crawl bằng tay từ curl trên terminal và crawl 30p lại phải ngắt quãng không họ chặn IP Vào Th 6, 11 thg 10, 2024 lúc 09:14 DestschEng ***@***.***> đã viết:

Cho mình hỏi là cái  url = 'https://shopee.vn/api/v4/pages/get_category_tree' nguồn gốc là trang nào trên shopee vậy ạ

**Comment by DestschEng** [comment]
Nếu dùng curl thì cho mình hỏi file create_tree_path.py dùng như nào vậy ạ

**Comment by Tran-Ngoc-Bao** [comment]
Có 1 api chứa cây danh mục họ open cho mình đấy bạn tìm mở dev tool tìm
trong fetch/xhr là thấy

Vào Th 6, 11 thg 10, 2024 lúc 10:24 DestschEng ***@***.***>
đã viết:

**Comment by DestschEng** [comment]
Cho mình hỏi mình dùng Curl đã truyền cookie thì vẫn bị lỗi {"is_customized":false,"is_login":false,"action_type":2,"error":90309999,"tracking_id":"443069dc1c5-6944-46ab-9f0b-646f60c0b69e"} không biết bạn có gặp phải vấn đề tương tự k ạ

**Comment by Tran-Ngoc-Bao** [comment]
Có đấy 🤣
Bạn phải copy curl từ dev tool đủ trường như trong file create_tree_path
của mình í

Vào Th 6, 11 thg 10, 2024 lúc 10:34 DestschEng ***@***.***>
đã viết:

**Comment by Tran-Ngoc-Bao** [comment]
Bạn nên đổi sang crawl từ Lazada hoặc Tiki họ không chặn đâu

Vào Th 6, 11 thg 10, 2024 lúc 10:36 Bảo Trần ***@***.***> đã
viết:

**Comment by DestschEng** [comment]
> Có đấy 🤣 Bạn phải copy curl từ dev tool đủ trường như trong file create_tree_path của mình í Vào Th 6, 11 thg 10, 2024 lúc 10:34 DestschEng ***@***.***> đã viết:
> […](#)
mình cũng copy từ devtool  nhưng trên devtool mình thấy trường này Af-Ac-Enc-Sz-Token: nó không hiển thị thì mà mình thấy trong file create_tree_path có giá trị token thì k biết là lấy nó ở đây vậy a

**Comment by Tran-Ngoc-Bao** [comment]
Copy as CURL có mà bạn nhỉ

Vào Th 6, 11 thg 10, 2024 lúc 10:48 DestschEng ***@***.***>
đã viết:

**Comment by DestschEng** [comment]
Giờ mình copy không thấy hiện Af-Ac-Enc-Sz-Token: nữa r :((((

curl 'https://shopee.vn/api/v4/pages/get_category_tree' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9,vi-VN;q=0.8,vi;q=0.7' \
  -H 'af-ac-enc-dat: 1bb0956add2af6c1' \
  -H 'af-ac-enc-sz-token;' \
  -H 'cookie: REC_T_ID=97ddafb1-9504-11ee-8b8c-0e8694b875c9; SPC_F=9Ubjd5IxOywVIJy5EIJPtx8uWcu70k3A;

**Comment by DestschEng** [comment]
> Copy as CURL có mà bạn nhỉ Vào Th 6, 11 thg 10, 2024 lúc 10:48 DestschEng ***@***.***> đã viết:

À mình chạy curl fetch được data rồi. Thank a lot bro

**Comment by Tran-Ngoc-Bao** [comment]
Bắt buộc lấy dữ liệu từ Shopee à bạn
Lấy từ Tiki hoặc Lazada không bị chặn cho sướng 🤣

Vào Th 6, 11 thg 10, 2024 lúc 11:04 DestschEng ***@***.***>
đã viết:

**Comment by DestschEng** [comment]
> Bắt buộc lấy dữ liệu từ Shopee à bạn Lấy từ Tiki hoặc Lazada không bị chặn cho sướng 🤣 Vào Th 6, 11 thg 10, 2024 lúc 11:04 DestschEng ***@***.***> đã viết:

À mình chỉ đang kiếm data mấy sàn thương mại điện tử để build data pipeline mà bị stuck thằng shopee may mà có repo bạn mới mò được lấy data bên shopee 

off topic không biết bạn có thể acpt connect linkedin của mình đc không [linkedin của mình](https://www.linkedin.com/in/ngy%E1%BB%85n-%C4%91%E1%BB%A9c-anh-9681152b5/) nãy mình có gửi connect
mình cũng đang theo data engineer nếu có tiện có thể trao đổi kiến thức đc k a
